import type { ArticleRecord, VideoRecord } from '../types/domain.js';

const now = '2026-06-11T10:00:00.000Z';

export const SEED_VIDEOS: VideoRecord[] = [
  {
    id: 'vid-practice-1',
    kinescopeId: 'demo-practice-morning',
    title: 'Утренняя хатха: мягкий старт',
    description: '60 минут практики для пробуждения тела и внимания.',
    category: 'practices',
    accessLevel: 'club_active',
    durationMin: 60,
    status: 'published',
    publishedAt: '2026-06-01T08:00:00.000Z',
    updatedAt: now,
  },
  {
    id: 'vid-practice-2',
    kinescopeId: 'demo-practice-evening',
    title: 'Вечернее восстановление',
    description: 'Практика на снятие напряжения и подготовку ко сну.',
    category: 'practices',
    accessLevel: 'club_active',
    durationMin: 75,
    status: 'published',
    publishedAt: '2026-06-05T19:30:00.000Z',
    updatedAt: now,
  },
  {
    id: 'vid-seminar-1',
    kinescopeId: 'demo-seminar-alignment',
    title: 'Семинар: выравнивание в асанах',
    description: 'Разбор ключевых точек внимания в базовых асанах.',
    category: 'seminars',
    accessLevel: 'club_active',
    durationMin: 90,
    status: 'published',
    publishedAt: '2026-06-08T11:00:00.000Z',
    updatedAt: now,
  },
  {
    id: 'vid-philosophy-1',
    kinescopeId: 'demo-philosophy-yoga-sutra',
    title: 'Йога-сутры: введение',
    description: 'Короткий разбор базовых понятий из первоисточников.',
    category: 'philosophy',
    accessLevel: 'club_active',
    durationMin: 45,
    status: 'published',
    publishedAt: '2026-06-10T12:00:00.000Z',
    updatedAt: now,
  },
];

export const SEED_ARTICLES: ArticleRecord[] = [
  {
    id: 'art-open-1',
    slug: 'kak-nachat-praktikovat',
    title: 'Как начать практиковать хатха-йогу дома',
    excerpt: 'Простые шаги для регулярной практики без перегруза.',
    body: 'Регулярность важнее интенсивности. Начните с коротких сессий 3 раза в неделю, следите за дыханием и не форсируйте амплитуду.',
    category: 'open',
    access: 'public',
    status: 'published',
    publishedAt: '2026-05-20T10:00:00.000Z',
    updatedAt: now,
  },
  {
    id: 'art-tech-1',
    slug: 'dyhanie-v-asane',
    title: 'Дыхание в асане: базовые ориентиры',
    excerpt: 'Клубный материал о связи дыхания и устойчивости в практике.',
    body: 'Дыхание — якорь внимания. В статических положениях сохраняйте ровный ритм, не задерживайте воздух на усилиях.',
    category: 'technique',
    access: 'club',
    status: 'published',
    publishedAt: '2026-06-02T10:00:00.000Z',
    updatedAt: now,
  },
  {
    id: 'art-life-1',
    slug: 'yoga-vne-kovrika',
    title: 'Йога вне коврика: внимание в быту',
    excerpt: 'Как перенести качество практики в повседневные действия.',
    body: 'Практика не заканчивается после «намасте». Замечайте осанку за столом, темп ходьбы и реакцию на стресс.',
    category: 'lifestyle',
    access: 'club',
    status: 'published',
    publishedAt: '2026-06-07T10:00:00.000Z',
    updatedAt: now,
  },
  {
    id: 'art-news-1',
    slug: 'raspisanie-iyun',
    title: 'Расписание клуба: ориентиры июня',
    excerpt: 'Ближайшие практики и семинары для участников клуба.',
    body: 'Три регулярные Zoom-практики в неделю плюс субботний углублённый блок. Записи появляются в библиотеке в течение суток.',
    category: 'club-news',
    access: 'club',
    status: 'published',
    publishedAt: '2026-06-01T09:00:00.000Z',
    updatedAt: now,
  },
];
